### ISSUE TITLE
Depricate HA core integration

### ISSUE THREAD

**Issue by zaped212** [jkeljo/hacs-greeneye-monitor#29]
While integrating my 2 GEM's into my HA install, I ran into issues as the documentation still points to using the HA core Green Eyed Monitor integration (https://www.home-assistant.io/integrations/greeneye_monitor).
Which sadly as I have learned... Is broken, after a few hours of trying to figure out why things were not working.

It would be highly beneficial if either the core integration was deprecated, or at least some additional information that points new users over to the HACS version.

**Comment by jkeljo** [comment]
Thanks for filing this issue, and I'm sorry you had a bad experience. 😢 

I agree with you that the core integration should either be removed or updated. I created the HACS version because updates to the core version were not getting traction. I tried to delete the core integration when I launched the HACS one (https://github.com/home-assistant/core/pull/93932). Unfortunately the core maintainers disagreed with that plan, and we also weren't able to come to an agreement that would unblock updates to the core integration.

So, at this point it's out of my control. The best place to file this issue is over at https://github.com/home-assistant/core/issues. Maybe now that the core integration has stopped working completely they'll take a different stance on removing it than they did earlier this year.

I'm sorry I don't have a better answer. 😞
