### ISSUE TITLE
Configure Default Display Resolution or add configuration to set default 

### ISSUE THREAD

**Issue by jkosharek** [jkeljo/hacs-greeneye-monitor#38]
With the display values of the properties brought over set to default, some seem to be a little odd, watts normally are 1-2 places but seem too often jump to 10-12 places or more to the right of zero and kWa seem to be displayed 14-16 places.

Could the integration be configured to display reasonable resolution or allow user configured display resolution at the integration level, like this?
Watts 0.0
Amps 0.00
kWh 0.000

**Comment by jkeljo** [comment]
That's a good point. I looked into it a bit. Turns out you can change it manually on a per-sensor basis since HA 2023.3, from the sensor settings (gear menu on the sensor details card). Apparently I can also set a default from the integration, which I haven't yet looked up how to do but is presumably not hard. I'll do it next time I have time to work on this!

**Comment by jkeljo** [comment]
This now has a reasonable default in https://github.com/jkeljo/hacs-greeneye-monitor/releases/tag/2024.2.19
