### ISSUE TITLE
Unable to reconfigure integration

### ISSUE THREAD

**Issue by alexkau** [jkeljo/hacs-greeneye-monitor#39]
## Describe the bug

When attempting to edit per-monitor options in order to add a new channel, the dropdown does not list my GEM's serial number (it is entirely empty), so I am unable to configure the new channel and add it as a sensor.

My configuration was automatically migrated from the old yaml configuration.

<img width="418" alt="image" src="https://github.com/jkeljo/hacs-greeneye-monitor/assets/471432/ab727ce9-75a9-4792-9268-380c7658bcf3">

## Diagnostics

[config_entry-greeneye_monitor-d704fb1bd20ee77833d33e7432c5b815.json.txt](https://github.com/jkeljo/hacs-greeneye-monitor/files/13687107/config_entry-greeneye_monitor-d704fb1bd20ee77833d33e7432c5b815.json.txt)

## Debug Logs

[home-assistant_greeneye_monitor_2023-12-15T15-59-13.113Z.log](https://github.com/jkeljo/hacs-greeneye-monitor/files/13687135/home-assistant_greeneye_monitor_2023-12-15T15-59-13.113Z.log)

**Comment by jkeljo** [comment]
That configuration dialog is only for changing the units of your pulse counters. Since your configuration was imported from YAML that didn't have pulse counters, the dialog doesn't show any monitors to choose from. That's a bug (#24).

But you said you want to add channels, which I assume means you've added more CTs to your GEM? Unlike the built-in integration, this integration creates entities for all channels of your GEM, regardless of whether you had configured them in your YAML. They have generic names like "sensor.gem_1121068_channel_31". By default each channel gets three entities, one each for current (amps), power (watts), and energy (kilowatt-hours). The current and power entities update every time a data packet comes in from the GEM and thus are disabled by default. The energy entities update much less frequently (I think every 30 minutes?) and are enabled by default.

So, all you need to do is go into entity settings for this integration and rename the generic names to something more meaningful to you. If you've set up InfluxDB for sensors that report a lot of data and you want power or current, you can enable those sensors from there too.

**Comment by alexkau** [comment]
Thanks again! My confusion was that the entity was missing from the list of enabled entities, and didn't think to check the integration and enable it. Everything's working correctly now.
