### ISSUE TITLE
No Configure options upon install via HACS

### ISSUE THREAD

**Issue by cbrollin** [jkeljo/hacs-greeneye-monitor#45]
## Describe the bug

After install via HACS, no entities or information is showing up. I try to check the configuration for GreenEye Monitor, but it gives this error. 

Config flow could not be loaded: {"message":"Handler OptionsFlowManager doesn't support step options_menu"}

I have redownloaded from HACS and restarted Home Assistant a few different times. Still the same error. I am setting up the port as in the GEM network utility.

Any help would be greatly appreciated. A bit new to the GEM.

## Diagnostics

[config_entry-greeneye_monitor-d50c1b4d3a4a28a9e33c7b4b7edf6dc3 (1).json](https://github.com/jkeljo/hacs-greeneye-monitor/files/15479205/config_entry-greeneye_monitor-d50c1b4d3a4a28a9e33c7b4b7edf6dc3.1.json)

**Comment by cbrollin** [comment]
I suspect this has to do with my configuration of GEM to home assistant. Trying to find a good guide on making sure that is correct. thanks.

**Comment by dstrohl** [comment]
In the initial post, @cbrollin was (at them time) unable to get any entities to  show up, but the config error I think is unrelated to that since I did get all of the entities showing up, but I'm still seeing the error.  Also @BenK22
noted that he  thought it might not be used for anything. (he also linked to a really good document on how to set it up).  

So, the question is, SHOULD there be anything under the "configure" link?  if so, it's broken and this bug is valid, if not, perhaps this is actually a feature request to just have a popup saying "nothing to see here, move along".
